---
- name: Install apache and start apache
  hosts: web
  become: yes # true # TRUE
  

  tasks:
    - name: Install apache
      dnf:
        name: httpd
        state: present
    - name: Start the apache
      service:
        name: httpd
        state: started
      tags:
        - install

    - name: Enabled the apache, post reboot will be started
      service:
        name: httpd
        enabled: yes # yes # on
    - name: Deploy a static page
      copy:
        src: "{{ source_path }}"
        dest: "{{ dest_path }}"
 
    - name: Modify the port from 8080 to "{{ LISTEN_PORT }}"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: "Listen {{ LISTEN_PORT }}"
      notify: 
        - ReStart the apache
  handlers:     
    - name: ReStart the apache
      service:
        name: httpd
        state: restarted
